j = {'contracts': {'balanceSituation': {'tuDisponible': {'listadoSaldosContratos': [{'clasificacion':
                                                                                         'CUENTAS_ORDINARIAS_Y_DIVISA',
                                                                                     'saldoAgregado': {
                                                                                         'codigoDivisa': 'EUR',
                                                                                         'divisa': '€',
                                                                                         'importe': 9010.46}},
                                                                                    {'clasificacion': 'PLAN_PENSION',
                                                                                     'saldoAgregado': {
                                                                                         'codigoDivisa': 'EUR',
                                                                                         'divisa': '€',
                                                                                         'importe': 2483.65}}],
                                                         'saldoAcumulado': {'codigoDivisa': 'EUR',
                                                                            'divisa': '€',
                                                                            'importe': 11494.11}},
                                        'tuFinanciacion': {
                                            'listadoSaldosContratos': [{'clasificacion': 'TARJETA_CREDITO',
                                                                        'saldoAgregado': {'codigoDivisa': 'EUR',
                                                                                          'divisa': '€',
                                                                                          'importe': 0.0}}],
                                            'saldoAcumulado': {'codigoDivisa': 'EUR',
                                                               'divisa': '€',
                                                               'importe': 0.0}}},
                   'contracts': [{'clasificacionesPermitidas': ['CUENTAS_ORDINARIAS_Y_DIVISA',
                                                                'CUENTAS_CREDITO_Y_CUENTAS_CREDITO_DIVISA'],
                                  'codigoContratoCcc': {'ccc': '0182-1150-05-0201568494',
                                                        'cccCadenaPlana': '01821150050201568494',
                                                        'cccWithoutMask': '0182-1150-05-0201568494'},
                                  'contractId': 'ES0182002000000000000000000405303614XXXXXXXXX',
                                  'contratoDto': {'administrablePorPlataformaGrupo': True,
                                                  'alias': ' ',
                                                  'bancoOficinaContrapartidaFolio': {'banco': '0182',
                                                                                     'bocf': '0182-1150-0020-156849',
                                                                                     'bocfAsPlainString': '018211500020156849',
                                                                                     'bocfFondosPlanes': '0182-1150-020-000156849',
                                                                                     'bocfValoresDepositos': '0182-1150-020-00156849',
                                                                                     'camposConcatenados': '018211500020156849',
                                                                                     'contrapartida': '0020',
                                                                                     'folio': '156849',
                                                                                     'oficina': '1150'},
                                                  'clasificacion': 'CUENTAS_ORDINARIAS_Y_DIVISA',
                                                  'clasificacionSaldos': 'Account',
                                                  'clasnombre': 'CUENTAS_ORDINARIAS_Y_DIVISA',
                                                  'codigoAplicacionGestora': '00',
                                                  'codigoClasificacionNivel1': '00001',
                                                  'codigoClasificacionNivel2': '00004',
                                                  'codigoClasificacionNivel3': '00056',
                                                  'codigoClasificacionNivel4': '',
                                                  'codigoClienteAutorizador': None,
                                                  'codigoDivisa': 'EUR',
                                                  'codigoEntidad': '0182',
                                                  'codigoExtensionContratoPadreCdpend': ' ',
                                                  'codigoISOPais': 'ES',
                                                  'consultasPermitidasBBVANet': True,
                                                  'consultasPermitidasBancaTelefonica': True,
                                                  'consultasPermitidasBbvaNet': True,
                                                  'consultasPermitidasCajero': True,
                                                  'consultasPermitidasSegunTipoIntervencion': True,
                                                  'cuentaExterna': '01821150050201568494',
                                                  'descripcionClasificacionNivel1': None,
                                                  'descripcionComercialProducto': 'CUENTA '
                                                                                  'ON '
                                                                                  'LINE',
                                                  'divisa': '€',
                                                  'fechaVencimiento': 253402214400000,
                                                  'id': 'ES0182002000000000000000000405303614XXXXXXXXX',
                                                  'identificadorProducto': '0CA0000245',
                                                  'identificadorUnicoDeContrato': '00000000000000000405303614',
                                                  'indicadorMancomunidad': 'UNIPERSONAL',
                                                  'indicadorVisualizacion': '',
                                                  'indiceContratoUsuarioActual': 0,
                                                  'mostrarEnPosicionGlobal': False,
                                                  'mostrarEnTuSituacion': True,
                                                  'nombreComercial': 'CUENTAS '
                                                                     'PERSONALES',
                                                  'operacionesPermitidasBBVANet': True,
                                                  'operacionesPermitidasBancaTelefonica': True,
                                                  'operacionesPermitidasBbvaNet': True,
                                                  'operacionesPermitidasCajero': True,
                                                  'operacionesPermitidasSegunTipoIntervencion': True,
                                                  'ordenTitularidad': 1,
                                                  'pintarQuieros': True,
                                                  'relacionTitularidad': 'TITULAR',
                                                  'relnombre': 'TITULAR',
                                                  'rutaImagen': '0CA0000245.png',
                                                  'tipoContrato': 'CUENTAS_ORDINARIAS_Y_DIVISA',
                                                  'tipoContratoBean': {'codigo': '00004',
                                                                       'nivel': 2},
                                                  'tipoPertenencia': None},
                                  'cuentaMetas': False,
                                  'iban': 'ES3701821150050201568494',
                                  'indicadorVisualizacion': '',
                                  'indiceDeProductoPadreEnListaProductos': -1,
                                  'indiceEnListaProductos': 0,
                                  'nombreComercial': '',
                                  'numeroProducto': '0182-1150-05-0201568494',
                                  'puedeRedomiciliarReciboBBVANet': False,
                                  'saldoActual': {'codigoDivisa': 'EUR',
                                                  'divisa': '€',
                                                  'importe': 9010.46},
                                  'saldoActualContraValor': None,
                                  'saldoDisponible': {'codigoDivisa': 'EUR',
                                                      'divisa': '€',
                                                      'importe': 9010.46},
                                  'saldoDisponibleContraValor': None,
                                  'tipoTitularidadEnumCodigo': 'TITULAR'},
                                 {'clasificacionesPermitidas': ['CUENTAS_ORDINARIAS_Y_DIVISA',
                                                                'CUENTAS_CREDITO_Y_CUENTAS_CREDITO_DIVISA'],
                                  'codigoContratoCcc': {'ccc': '0182-1150-08-0208525159',
                                                        'cccCadenaPlana': '01821150080208525159',
                                                        'cccWithoutMask': '0182-1150-08-0208525159'},
                                  'contractId': 'ES0182002000000000000000000002196573XXXXXXXXX',
                                  'contratoDto': {'administrablePorPlataformaGrupo': True,
                                                  'alias': ' ',
                                                  'bancoOficinaContrapartidaFolio': {'banco': '0182',
                                                                                     'bocf': '0182-1150-0020-852515',
                                                                                     'bocfAsPlainString': '018211500020852515',
                                                                                     'bocfFondosPlanes': '0182-1150-020-000852515',
                                                                                     'bocfValoresDepositos': '0182-1150-020-00852515',
                                                                                     'camposConcatenados': '018211500020852515',
                                                                                     'contrapartida': '0020',
                                                                                     'folio': '852515',
                                                                                     'oficina': '1150'},
                                                  'clasificacion': 'CUENTAS_ORDINARIAS_Y_DIVISA',
                                                  'clasificacionSaldos': 'Account',
                                                  'clasnombre': 'CUENTAS_ORDINARIAS_Y_DIVISA',
                                                  'codigoAplicacionGestora': '00',
                                                  'codigoClasificacionNivel1': '00001',
                                                  'codigoClasificacionNivel2': '00004',
                                                  'codigoClasificacionNivel3': '00056',
                                                  'codigoClasificacionNivel4': '',
                                                  'codigoClienteAutorizador': None,
                                                  'codigoDivisa': 'EUR',
                                                  'codigoEntidad': '0182',
                                                  'codigoExtensionContratoPadreCdpend': ' ',
                                                  'codigoISOPais': 'ES',
                                                  'consultasPermitidasBBVANet': False,
                                                  'consultasPermitidasBancaTelefonica': False,
                                                  'consultasPermitidasBbvaNet': False,
                                                  'consultasPermitidasCajero': False,
                                                  'consultasPermitidasSegunTipoIntervencion': True,
                                                  'cuentaExterna': '01821150080208525159',
                                                  'descripcionClasificacionNivel1': None,
                                                  'descripcionComercialProducto': 'CUENTA '
                                                                                  'BLUE',
                                                  'divisa': '€',
                                                  'fechaVencimiento': -62135769600000,
                                                  'id': 'ES0182002000000000000000000002196573XXXXXXXXX',
                                                  'identificadorProducto': '0CA0000079',
                                                  'identificadorUnicoDeContrato': '00000000000000000002196573',
                                                  'indicadorMancomunidad': 'UNIPERSONAL',
                                                  'indicadorVisualizacion': '',
                                                  'indiceContratoUsuarioActual': 0,
                                                  'mostrarEnPosicionGlobal': False,
                                                  'mostrarEnTuSituacion': False,
                                                  'nombreComercial': 'CUENTAS '
                                                                     'PERSONALES',
                                                  'operacionesPermitidasBBVANet': False,
                                                  'operacionesPermitidasBancaTelefonica': False,
                                                  'operacionesPermitidasBbvaNet': False,
                                                  'operacionesPermitidasCajero': False,
                                                  'operacionesPermitidasSegunTipoIntervencion': True,
                                                  'ordenTitularidad': 2,
                                                  'pintarQuieros': True,
                                                  'relacionTitularidad': 'REPRESENTANTE',
                                                  'relnombre': 'REPRESENTANTE',
                                                  'rutaImagen': '0CA0000079.png',
                                                  'tipoContrato': 'CUENTAS_ORDINARIAS_Y_DIVISA',
                                                  'tipoContratoBean': {'codigo': '00004',
                                                                       'nivel': 2},
                                                  'tipoPertenencia': None},
                                  'cuentaMetas': False,
                                  'iban': 'ES1701821150080208525159',
                                  'indicadorVisualizacion': '',
                                  'indiceDeProductoPadreEnListaProductos': -1,
                                  'indiceEnListaProductos': 1,
                                  'nombreComercial': '',
                                  'numeroProducto': '0182-1150-08-0208525159',
                                  'puedeRedomiciliarReciboBBVANet': False,
                                  'saldoActual': None,
                                  'saldoActualContraValor': None,
                                  'saldoDisponible': None,
                                  'saldoDisponibleContraValor': None,
                                  'tipoTitularidadEnumCodigo': 'R_LEGAL'},
                                 {'activada': True,
                                  'beneficiario': None,
                                  'clasificacionesPermitidas': ['TARJETA',
                                                                'TARJETA_DEBITO'],
                                  'codigoContratoTarjetasPan': '5181760004611421',
                                  'codigoEquipo': None,
                                  'contractId': 'ES0182061600000000000000000270546984XXXXXXXXX',
                                  'contratoDto': {'administrablePorPlataformaGrupo': False,
                                                  'alias': ' ',
                                                  'bancoOficinaContrapartidaFolio': {'banco': '0182',
                                                                                     'bocf': '0182-1150-0616-20437694',
                                                                                     'bocfAsPlainString': '01821150061620437694',
                                                                                     'bocfFondosPlanes': '0182-1150-616-020437694',
                                                                                     'bocfValoresDepositos': '0182-1150-616-20437694',
                                                                                     'camposConcatenados': '01821150061620437694',
                                                                                     'contrapartida': '0616',
                                                                                     'folio': '20437694',
                                                                                     'oficina': '1150'},
                                                  'clasificacion': 'TARJETA_DEBITO',
                                                  'clasificacionSaldos': 'DebitCard',
                                                  'clasnombre': 'TARJETA_DEBITO',
                                                  'codigoAplicacionGestora': ' ',
                                                  'codigoClasificacionNivel1': '00001',
                                                  'codigoClasificacionNivel2': '00005',
                                                  'codigoClasificacionNivel3': '00022',
                                                  'codigoClasificacionNivel4': '',
                                                  'codigoClienteAutorizador': None,
                                                  'codigoDivisa': 'EUR',
                                                  'codigoEntidad': '0182',
                                                  'codigoExtensionContratoPadreCdpend': '000000001',
                                                  'codigoISOPais': 'ES',
                                                  'consultasPermitidasBBVANet': True,
                                                  'consultasPermitidasBancaTelefonica': True,
                                                  'consultasPermitidasBbvaNet': True,
                                                  'consultasPermitidasCajero': True,
                                                  'consultasPermitidasSegunTipoIntervencion': True,
                                                  'cuentaExterna': '5181760004611421',
                                                  'descripcionClasificacionNivel1': None,
                                                  'descripcionComercialProducto': 'TARJETA '
                                                                                  'AHORA '
                                                                                  'MASTERCARD',
                                                  'divisa': '€',
                                                  'fechaVencimiento': -62135769600000,
                                                  'id': 'ES0182061600000000000000000270546984XXXXXXXXX',
                                                  'identificadorProducto': '0000011176',
                                                  'identificadorUnicoDeContrato': '00000000000000000270546984',
                                                  'indicadorMancomunidad': 'SOLIDARIO',
                                                  'indicadorVisualizacion': '',
                                                  'indiceContratoUsuarioActual': 0,
                                                  'mostrarEnPosicionGlobal': False,
                                                  'mostrarEnTuSituacion': True,
                                                  'nombreComercial': 'DEBITO',
                                                  'operacionesPermitidasBBVANet': True,
                                                  'operacionesPermitidasBancaTelefonica': True,
                                                  'operacionesPermitidasBbvaNet': True,
                                                  'operacionesPermitidasCajero': True,
                                                  'operacionesPermitidasSegunTipoIntervencion': True,
                                                  'ordenTitularidad': 1,
                                                  'pintarQuieros': True,
                                                  'relacionTitularidad': 'TITULAR',
                                                  'relnombre': 'TITULAR',
                                                  'rutaImagen': '00001.png',
                                                  'tipoContrato': 'TARJETA_DEBITO',
                                                  'tipoContratoBean': {'codigo': '00022',
                                                                       'nivel': 3},
                                                  'tipoPertenencia': None},
                                  'cuentaAsociada': None,
                                  'fechaCaducidad': '01-01-0001',
                                  'fechaEstampacion': '20151211',
                                  'indicadorEstado': ' ',
                                  'indiceDeProductoPadreEnListaProductos': -1,
                                  'indiceEnListaProductos': 2,
                                  'legacyOffer': '0000',
                                  'legacyProduct': '3096',
                                  'logadoPanAnonimo': False,
                                  'noClicable': False,
                                  'nombreComercial': '',
                                  'numeroProducto': '5181760004611421',
                                  'saldoDisponible': {'codigoDivisa': 'EUR',
                                                      'divisa': '€',
                                                      'importe': 0.0},
                                  'saldoGastado': None,
                                  'sticker': False,
                                  'tarjetaAnonima': False,
                                  'tienePanCorto': False,
                                  'tipoDeTarjeta': 'P',
                                  'tipoMigracion': ' ',
                                  'tipoTitularidadEnumCodigo': 'TITULAR',
                                  'titular': None},
                                 {'activada': True,
                                  'beneficiario': None,
                                  'clasificacionesPermitidas': ['TARJETA',
                                                                'TARJETA_DEBITO'],
                                  'codigoContratoTarjetasPan': '5181760022542533',
                                  'codigoEquipo': None,
                                  'contractId': 'ES0182061600000000000000000415242973XXXXXXXXX',
                                  'contratoDto': {'administrablePorPlataformaGrupo': False,
                                                  'alias': ' ',
                                                  'bancoOficinaContrapartidaFolio': {'banco': '0182',
                                                                                     'bocf': '0182-1150-0616-32887249',
                                                                                     'bocfAsPlainString': '01821150061632887249',
                                                                                     'bocfFondosPlanes': '0182-1150-616-032887249',
                                                                                     'bocfValoresDepositos': '0182-1150-616-32887249',
                                                                                     'camposConcatenados': '01821150061632887249',
                                                                                     'contrapartida': '0616',
                                                                                     'folio': '32887249',
                                                                                     'oficina': '1150'},
                                                  'clasificacion': 'TARJETA_DEBITO',
                                                  'clasificacionSaldos': 'DebitCard',
                                                  'clasnombre': 'TARJETA_DEBITO',
                                                  'codigoAplicacionGestora': ' ',
                                                  'codigoClasificacionNivel1': '00001',
                                                  'codigoClasificacionNivel2': '00005',
                                                  'codigoClasificacionNivel3': '00022',
                                                  'codigoClasificacionNivel4': '',
                                                  'codigoClienteAutorizador': None,
                                                  'codigoDivisa': 'EUR',
                                                  'codigoEntidad': '0182',
                                                  'codigoExtensionContratoPadreCdpend': '000000001',
                                                  'codigoISOPais': 'ES',
                                                  'consultasPermitidasBBVANet': True,
                                                  'consultasPermitidasBancaTelefonica': True,
                                                  'consultasPermitidasBbvaNet': True,
                                                  'consultasPermitidasCajero': True,
                                                  'consultasPermitidasSegunTipoIntervencion': True,
                                                  'cuentaExterna': '5181760022542533',
                                                  'descripcionClasificacionNivel1': None,
                                                  'descripcionComercialProducto': 'TARJETA '
                                                                                  'AHORA '
                                                                                  'MASTERCARD',
                                                  'divisa': '€',
                                                  'fechaVencimiento': -62135769600000,
                                                  'id': 'ES0182061600000000000000000415242973XXXXXXXXX',
                                                  'identificadorProducto': '0000009719',
                                                  'identificadorUnicoDeContrato': '00000000000000000415242973',
                                                  'indicadorMancomunidad': 'SOLIDARIO',
                                                  'indicadorVisualizacion': '',
                                                  'indiceContratoUsuarioActual': 0,
                                                  'mostrarEnPosicionGlobal': False,
                                                  'mostrarEnTuSituacion': True,
                                                  'nombreComercial': 'DEBITO',
                                                  'operacionesPermitidasBBVANet': True,
                                                  'operacionesPermitidasBancaTelefonica': True,
                                                  'operacionesPermitidasBbvaNet': True,
                                                  'operacionesPermitidasCajero': True,
                                                  'operacionesPermitidasSegunTipoIntervencion': True,
                                                  'ordenTitularidad': 1,
                                                  'pintarQuieros': True,
                                                  'relacionTitularidad': 'TITULAR',
                                                  'relnombre': 'TITULAR',
                                                  'rutaImagen': '00001.png',
                                                  'tipoContrato': 'TARJETA_DEBITO',
                                                  'tipoContratoBean': {'codigo': '00022',
                                                                       'nivel': 3},
                                                  'tipoPertenencia': None},
                                  'cuentaAsociada': None,
                                  'fechaCaducidad': '01-01-0001',
                                  'fechaEstampacion': '20180924',
                                  'indicadorEstado': ' ',
                                  'indiceDeProductoPadreEnListaProductos': -1,
                                  'indiceEnListaProductos': 3,
                                  'legacyOffer': '0000',
                                  'legacyProduct': '9929',
                                  'logadoPanAnonimo': False,
                                  'noClicable': False,
                                  'nombreComercial': '',
                                  'numeroProducto': '5181760022542533',
                                  'saldoDisponible': {'codigoDivisa': 'EUR',
                                                      'divisa': '€',
                                                      'importe': 0.0},
                                  'saldoGastado': None,
                                  'sticker': False,
                                  'tarjetaAnonima': False,
                                  'tienePanCorto': False,
                                  'tipoDeTarjeta': 'P',
                                  'tipoMigracion': ' ',
                                  'tipoTitularidadEnumCodigo': 'TITULAR',
                                  'titular': None},
                                 {'activada': False,
                                  'clasificacionesPermitidas': ['TARJETA_COMPLEMENTARIA',
                                                                'TARJETA_CREDITO',
                                                                'TARJETA',
                                                                'TARJETA_SENDO',
                                                                'VIA_T',
                                                                'REVOLVING',
                                                                'DIEZ'],
                                  'codigoContratoTarjetasPan': '4940005051189748',
                                  'codigoEquipo': None,
                                  'contractId': 'ES0182061500000000000000000039524416XXXXXXXXX',
                                  'contratoDto': {'administrablePorPlataformaGrupo': False,
                                                  'alias': ' ',
                                                  'bancoOficinaContrapartidaFolio': {'banco': '0182',
                                                                                     'bocf': '0182-1150-0615-4272610',
                                                                                     'bocfAsPlainString': '0182115006154272610',
                                                                                     'bocfFondosPlanes': '0182-1150-615-004272610',
                                                                                     'bocfValoresDepositos': '0182-1150-615-04272610',
                                                                                     'camposConcatenados': '0182115006154272610',
                                                                                     'contrapartida': '0615',
                                                                                     'folio': '4272610',
                                                                                     'oficina': '1150'},
                                                  'clasificacion': 'TARJETA_CREDITO',
                                                  'clasificacionSaldos': 'CreditCard',
                                                  'clasnombre': 'TARJETA_CREDITO',
                                                  'codigoAplicacionGestora': ' ',
                                                  'codigoClasificacionNivel1': '00002',
                                                  'codigoClasificacionNivel2': '00016',
                                                  'codigoClasificacionNivel3': '00029',
                                                  'codigoClasificacionNivel4': '',
                                                  'codigoClienteAutorizador': None,
                                                  'codigoDivisa': 'EUR',
                                                  'codigoEntidad': '0182',
                                                  'codigoExtensionContratoPadreCdpend': '000000001',
                                                  'codigoISOPais': 'ES',
                                                  'consultasPermitidasBBVANet': True,
                                                  'consultasPermitidasBancaTelefonica': True,
                                                  'consultasPermitidasBbvaNet': True,
                                                  'consultasPermitidasCajero': True,
                                                  'consultasPermitidasSegunTipoIntervencion': True,
                                                  'cuentaExterna': '4940005051189748',
                                                  'descripcionClasificacionNivel1': None,
                                                  'descripcionComercialProducto': 'TARJETA '
                                                                                  'DESPUES '
                                                                                  'BBVA',
                                                  'divisa': '€',
                                                  'fechaVencimiento': -62135769600000,
                                                  'id': 'ES0182061500000000000000000039524416XXXXXXXXX',
                                                  'identificadorProducto': '0000001314',
                                                  'identificadorUnicoDeContrato': '00000000000000000039524416',
                                                  'indicadorMancomunidad': 'SOLIDARIO',
                                                  'indicadorVisualizacion': '',
                                                  'indiceContratoUsuarioActual': 0,
                                                  'mostrarEnPosicionGlobal': False,
                                                  'mostrarEnTuSituacion': True,
                                                  'nombreComercial': 'CREDITO',
                                                  'operacionesPermitidasBBVANet': True,
                                                  'operacionesPermitidasBancaTelefonica': True,
                                                  'operacionesPermitidasBbvaNet': True,
                                                  'operacionesPermitidasCajero': True,
                                                  'operacionesPermitidasSegunTipoIntervencion': True,
                                                  'ordenTitularidad': 1,
                                                  'pintarQuieros': True,
                                                  'relacionTitularidad': 'TITULAR',
                                                  'relnombre': 'TITULAR',
                                                  'rutaImagen': '00002.png',
                                                  'tipoContrato': 'TARJETA_CREDITO',
                                                  'tipoContratoBean': {'codigo': '00029',
                                                                       'nivel': 3},
                                                  'tipoPertenencia': None},
                                  'cuentaAsociada': None,
                                  'fechaCaducidad': '01-01-0001',
                                  'fechaEstampacion': '20150724',
                                  'indicadorEstado': 'K',
                                  'indiceDeProductoPadreEnListaProductos': -1,
                                  'indiceEnListaProductos': 6,
                                  'legacyOffer': '0000',
                                  'legacyProduct': '2369',
                                  'limiteCredito': {'codigoDivisa': 'EUR',
                                                    'divisa': '€',
                                                    'importe': 600.0},
                                  'logadoPanAnonimo': False,
                                  'noClicable': False,
                                  'nombreComercial': '',
                                  'numeroProducto': '4940005051189748',
                                  'panTarjetaMadre': None,
                                  'saldoCredito': {'codigoDivisa': 'EUR',
                                                   'divisa': '€',
                                                   'importe': 0.0},
                                  'saldoDisponible': {'codigoDivisa': 'EUR',
                                                      'divisa': '€',
                                                      'importe': 600.0},
                                  'sticker': False,
                                  'tarjetaAnonima': False,
                                  'tarjetaAnticipo': False,
                                  'tienePanCorto': False,
                                  'tipoDeTarjeta': 'P',
                                  'tipoMigracion': ' ',
                                  'tipoTitularidadEnumCodigo': 'TITULAR',
                                  'titular': None,
                                  'uicTarjetaMadre': None},
                                 {'clasificacionesPermitidas': ['EPSVS',
                                                                'PLAN_INDIVIDUAL'],
                                  'contractId': 'ES9184080000000000000000000372995291XXXXXXXXX',
                                  'contratoDto': {'administrablePorPlataformaGrupo': False,
                                                  'alias': ' ',
                                                  'bancoOficinaContrapartidaFolio': {'banco': '0182',
                                                                                     'bocf': '0182-1150-0800-7263305',
                                                                                     'bocfAsPlainString': '0182115008007263305',
                                                                                     'bocfFondosPlanes': '0182-1150-800-007263305',
                                                                                     'bocfValoresDepositos': '0182-1150-800-07263305',
                                                                                     'camposConcatenados': '0182115008007263305',
                                                                                     'contrapartida': '0800',
                                                                                     'folio': '7263305',
                                                                                     'oficina': '1150'},
                                                  'clasificacion': 'PLAN_INDIVIDUAL',
                                                  'clasificacionSaldos': 'PensionPlan',
                                                  'clasnombre': 'PLAN_INDIVIDUAL',
                                                  'codigoAplicacionGestora': ' ',
                                                  'codigoClasificacionNivel1': '00001',
                                                  'codigoClasificacionNivel2': '00009',
                                                  'codigoClasificacionNivel3': '00027',
                                                  'codigoClasificacionNivel4': '',
                                                  'codigoClienteAutorizador': None,
                                                  'codigoDivisa': None,
                                                  'codigoEntidad': '9184',
                                                  'codigoExtensionContratoPadreCdpend': ' ',
                                                  'codigoISOPais': 'ES',
                                                  'consultasPermitidasBBVANet': True,
                                                  'consultasPermitidasBancaTelefonica': True,
                                                  'consultasPermitidasBbvaNet': True,
                                                  'consultasPermitidasCajero': True,
                                                  'consultasPermitidasSegunTipoIntervencion': True,
                                                  'cuentaExterna': ' ',
                                                  'descripcionClasificacionNivel1': None,
                                                  'descripcionComercialProducto': 'BBVA '
                                                                                  'PLAN '
                                                                                  'MERCADO '
                                                                                  'MONETARIO, '
                                                                                  'PPI',
                                                  'divisa': None,
                                                  'fechaVencimiento': -62135769600000,
                                                  'id': 'ES9184080000000000000000000372995291XXXXXXXXX',
                                                  'identificadorProducto': '0000000908',
                                                  'identificadorUnicoDeContrato': '00000000000000000372995291',
                                                  'indicadorMancomunidad': 'UNIPERSONAL',
                                                  'indicadorVisualizacion': '',
                                                  'indiceContratoUsuarioActual': 0,
                                                  'mostrarEnPosicionGlobal': False,
                                                  'mostrarEnTuSituacion': True,
                                                  'nombreComercial': 'BBVA PLAN '
                                                                     'MERCADO '
                                                                     'MONETARIO, '
                                                                     'PPI',
                                                  'operacionesPermitidasBBVANet': True,
                                                  'operacionesPermitidasBancaTelefonica': True,
                                                  'operacionesPermitidasBbvaNet': True,
                                                  'operacionesPermitidasCajero': True,
                                                  'operacionesPermitidasSegunTipoIntervencion': True,
                                                  'ordenTitularidad': 1,
                                                  'pintarQuieros': True,
                                                  'relacionTitularidad': 'TITULAR',
                                                  'relnombre': 'TITULAR',
                                                  'rutaImagen': '00009.png',
                                                  'tipoContrato': 'PLAN_INDIVIDUAL',
                                                  'tipoContratoBean': {'codigo': '00027',
                                                                       'nivel': 3},
                                                  'tipoPertenencia': None},
                                  'derechosConsolidados': {'codigoDivisa': 'EUR',
                                                           'divisa': '€',
                                                           'importe': 34.21},
                                  'indiceDeProductoPadreEnListaProductos': -1,
                                  'indiceEnListaProductos': 4,
                                  'nombre': None,
                                  'nombreComercial': '',
                                  'numeroParticipaciones': 29.7180015,
                                  'numeroProducto': '0182115008007263305',
                                  'tipoTitularidadEnumCodigo': 'TITULAR',
                                  'valorParticipacion': {'codigoDivisa': 'EUR',
                                                         'divisa': '€',
                                                         'importe': 1.151087}},
                                 {'clasificacionesPermitidas': ['EPSVS',
                                                                'PLAN_INDIVIDUAL'],
                                  'contractId': 'ES9184080000000000000000000256847898XXXXXXXXX',
                                  'contratoDto': {'administrablePorPlataformaGrupo': False,
                                                  'alias': ' ',
                                                  'bancoOficinaContrapartidaFolio': {'banco': '0182',
                                                                                     'bocf': '0182-1150-0800-5338138',
                                                                                     'bocfAsPlainString': '0182115008005338138',
                                                                                     'bocfFondosPlanes': '0182-1150-800-005338138',
                                                                                     'bocfValoresDepositos': '0182-1150-800-05338138',
                                                                                     'camposConcatenados': '0182115008005338138',
                                                                                     'contrapartida': '0800',
                                                                                     'folio': '5338138',
                                                                                     'oficina': '1150'},
                                                  'clasificacion': 'PLAN_INDIVIDUAL',
                                                  'clasificacionSaldos': 'PensionPlan',
                                                  'clasnombre': 'PLAN_INDIVIDUAL',
                                                  'codigoAplicacionGestora': '00',
                                                  'codigoClasificacionNivel1': '00001',
                                                  'codigoClasificacionNivel2': '00009',
                                                  'codigoClasificacionNivel3': '00027',
                                                  'codigoClasificacionNivel4': '',
                                                  'codigoClienteAutorizador': None,
                                                  'codigoDivisa': 'EUR',
                                                  'codigoEntidad': '9184',
                                                  'codigoExtensionContratoPadreCdpend': ' ',
                                                  'codigoISOPais': 'ES',
                                                  'consultasPermitidasBBVANet': True,
                                                  'consultasPermitidasBancaTelefonica': True,
                                                  'consultasPermitidasBbvaNet': True,
                                                  'consultasPermitidasCajero': True,
                                                  'consultasPermitidasSegunTipoIntervencion': True,
                                                  'cuentaExterna': ' ',
                                                  'descripcionClasificacionNivel1': None,
                                                  'descripcionComercialProducto': 'BBVA '
                                                                                  'PLAN '
                                                                                  'MULTIACTIVO '
                                                                                  'DECIDIDO',
                                                  'divisa': '€',
                                                  'fechaVencimiento': -62135769600000,
                                                  'id': 'ES9184080000000000000000000256847898XXXXXXXXX',
                                                  'identificadorProducto': '0000007778',
                                                  'identificadorUnicoDeContrato': '00000000000000000256847898',
                                                  'indicadorMancomunidad': 'SOLIDARIO',
                                                  'indicadorVisualizacion': '',
                                                  'indiceContratoUsuarioActual': 0,
                                                  'mostrarEnPosicionGlobal': False,
                                                  'mostrarEnTuSituacion': True,
                                                  'nombreComercial': 'BBVA PLAN '
                                                                     'MULTIACTIVO '
                                                                     'DECIDIDO',
                                                  'operacionesPermitidasBBVANet': True,
                                                  'operacionesPermitidasBancaTelefonica': True,
                                                  'operacionesPermitidasBbvaNet': True,
                                                  'operacionesPermitidasCajero': True,
                                                  'operacionesPermitidasSegunTipoIntervencion': True,
                                                  'ordenTitularidad': 1,
                                                  'pintarQuieros': True,
                                                  'relacionTitularidad': 'TITULAR',
                                                  'relnombre': 'TITULAR',
                                                  'rutaImagen': '00009.png',
                                                  'tipoContrato': 'PLAN_INDIVIDUAL',
                                                  'tipoContratoBean': {'codigo': '00027',
                                                                       'nivel': 3},
                                                  'tipoPertenencia': None},
                                  'derechosConsolidados': {'codigoDivisa': 'EUR',
                                                           'divisa': '€',
                                                           'importe': 2449.44},
                                  'indiceDeProductoPadreEnListaProductos': -1,
                                  'indiceEnListaProductos': 5,
                                  'nombre': None,
                                  'nombreComercial': '',
                                  'numeroParticipaciones': 2091.9947985,
                                  'numeroProducto': '0182115008005338138',
                                  'tipoTitularidadEnumCodigo': 'TITULAR',
                                  'valorParticipacion': {'codigoDivisa': 'EUR',
                                                         'divisa': '€',
                                                         'importe': 1.170861}}],
                   'visualizadores': False},
     'languages': [{'langCode': 'CAS', 'language': 'ES'},
                   {'langCode': 'ENG', 'language': 'EN'},
                   {'langCode': 'CAT', 'language': 'CA'}],
     'logonForm': {'browserUrl': '/particulares',
                   'campania': None,
                   'campaniaBloqueante': None,
                   'campaniasDisponibles': None,
                   'customerId': 'ES0182003629321C',
                   'ivrOTP': None,
                   'lastUpdateTimeStamp': 1549553314883,
                   'operacionAdicional': None,
                   'operacionCodigoError': None,
                   'operacionMensaje': None,
                   'operacionResultado': 'OK',
                   'scCodigoCliente': '003629321',
                   'scUserId': '++Qaghmw6SVLHpJEd2ITmxJrzxOA1lE8',
                   'signatureIvr': None,
                   'ttClientId': '++Qaghmw6SVLHpJEd2ITmxJrzxOA1lE8',
                   'ttUserId': '',
                   'ttVisitorId': '',
                   'view': ''},
     'propertiesAll': {'appConfig': {'accesoUsuarioAltaExpress': True,
                                     'accessCodeToggle': True,
                                     'accountRetentionsClientflowView': False,
                                     'accountRetentionsEnabled': True,
                                     'accountsFlowMeter': False,
                                     'accountsToggle': True,
                                     'activaAnticipoNominaOneClick': True,
                                     'activarCrs': True,
                                     'addressesToggle': True,
                                     'alertasCuentas': False,
                                     'alertasTarjetas': False,
                                     'altaClienteDNIe': True,
                                     'altaPlanesImagenCampana': 'https://www.bbva.es/sistema/bannerCampaniaPlanesAlta.jsp',
                                     'altaPlanesImagenNoCampana': 'https://www.bbva.es/sistema/bannerNoCampaniaPlanesAlta.jsp',
                                     'alwaysAliveSession': True,
                                     'aperturaBabyPlanner': True,
                                     'aportacionExtraImagenCampana': 'https://www.bbva.es/sistema/bannerCampaniaPlanesExtra.jsp',
                                     'aportacionExtraImagenNoCampana': 'https://www.bbva.es/sistema/bannerNoCampaniaPlanesExtra.jsp',
                                     'aportacionPeriodicaImagenCampana': 'https://www.bbva.es/sistema/bannerCampaniaPlanesPeriodicas.jsp',
                                     'aportacionPeriodicaImagenNoCampana': 'https://www.bbva.es/sistema/bannerNoCampaniaPlanesPeriodicas.jsp',
                                     'apoyoCampania': True,
                                     'asoMaxConfigurableTimeout': 20000,
                                     'asoReadTimeout': 10000,
                                     'asoRestHost': 'https://www.bbva.es/ASO',
                                     'bDelegacionVotoActivo': False,
                                     'barraAutoHidden': True,
                                     'bloqueoOperacionesPorRbaOFatcaActivo': True,
                                     'c2cEnabled': True,
                                     'c2cNuevo': True,
                                     'c2cRecoverPassword': True,
                                     'cajaRiskAssessment': False,
                                     'cambioAliasProductoToggle': True,
                                     'cambioCorrespondenciaPostalProductoToggle': True,
                                     'cambioDireccionAsociadaProductoToggle': True,
                                     'cambioIndicadoresProductoToggle': True,
                                     'cambioOficina': True,
                                     'cambiosEfectivoMovil': True,
                                     'campaniasPPI': True,
                                     'careSegurosDocumentos': True,
                                     'chatGestorNewEnabled': False,
                                     'citaPreviaMostrarTelefonoGestor': True,
                                     'clientFlowFatcaRoutes': ['cuentas/:producto/transferenciasnueva',
                                                               'cuentas/:producto/transferenciasinternacionales',
                                                               'cuentas/:producto/recargatarjeta',
                                                               'cuentas/:producto/transferenciasgestion',
                                                               'cuentas/:producto/efectivomovil',
                                                               'cuentas/:producto/recargamovil',
                                                               'cuentas/:producto/recargatarjetavirtual',
                                                               'tarjetas/:producto/descargartarjeta',
                                                               'financial-aggregator_enrollment'],
                                     'clientFlowRoutes': ['tarjetas/:producto/gestionarpagospersonalizados',
                                                          'fondosinternacionales/:producto/ficha',
                                                          'fondosinternacionales/:producto/ficha/:operativa',
                                                          'fondosinternacionales/:producto/fichagestora'],
                                     'clientResourcesNewPGActive': True,
                                     'closeSessionOnBrowserClossingEnabled': False,
                                     'comunicacionBuzonToggle': True,
                                     'contactsBookToggle': True,
                                     'controlAccesoMifid': 'true',
                                     'controlAreapersonalBuzonMostrarContratos': False,
                                     'controlCambiosAltaCita': True,
                                     'controlCertificacionEstrategicaLOPD': True,
                                     'controlCorrespondenciaVirtualMensajesPdf': True,
                                     'controlDeAjustesPlanes': True,
                                     'controlDeclaracionConjunta': True,
                                     'controlEliminarAportacionInicialPorEca': True,
                                     'controlEnvioDocumentos': True,
                                     'controlErroresCertificacionEstrategicaContratoMulticanal': True,
                                     'controlNormativoEtfs': False,
                                     'controlPagos': True,
                                     'controlPlanesOneclick': True,
                                     'controlProductoFamilia': True,
                                     'controlProductoFamiliaComboAutorizado': True,
                                     'controlTarjetaLiga': True,
                                     'controlTraspasoExterno': True,
                                     'controlWidgetPatrimonio': True,
                                     'correspondenciaVirtualBusqueda': True,
                                     'cvConfigToggle': True,
                                     'dataLayerEnable': True,
                                     'dataLayerTimeout': '3000',
                                     'decimalesFondosPlanes': True,
                                     'depositsToggle': True,
                                     'desarrolloNoModalCRMLopddae': True,
                                     'disclaimerCancelacionParcialHipoteca': True,
                                     'domiciliacionesToggle': True,
                                     'duplicatedsessioncontrolenabled': False,
                                     'eliminacionConfirmacionEmail': True,
                                     'enableBlockUserOperationsWhenLackData': True,
                                     'enableFatca': True,
                                     'enableFatcaRbaInfo': True,
                                     'enableModalMovementType': True,
                                     'enableTabletFeatures': True,
                                     'enaxAgileOperationsWidgetToggle': False,
                                     'enaxCardSheetToggle': True,
                                     'enaxCashTransferToggle': True,
                                     'enaxSecuritiesRealTimeSecurityQuote': False,
                                     'enaxSecuritiesToggle': True,
                                     'enaxTransferToCardToggle': True,
                                     'enaxTransfersToggle': True,
                                     'enlacesCarterasAsesoradasActivo': True,
                                     'enlacesCarterasGestionadasActivo': False,
                                     'fatcaOpenModalTimeout': '1000',
                                     'fatcaTimeout': '5000',
                                     'fichaGestoraFondosInternacionalesQFunds': True,
                                     'fondosMifid': True,
                                     'gestionDirecciones': True,
                                     'gestionDireccionesProducto': True,
                                     'gestionarPagosPersonalizadosToggle': True,
                                     'getUserContextualDataV2Active': True,
                                     'getUserContextualDataV2CustomerIds': '',
                                     'getUserContextualDataV2CustomerIdsEnds': '0|1|2|3|4|5|6|7|8|9',
                                     'getUserContextualDataV2Toggle': True,
                                     'hasPendingTasksActive': True,
                                     'hazteClienteOficinaUnica': '9465',
                                     'iconosFicha': True,
                                     'impuestosEstatales': False,
                                     'infoCrmPlanes': True,
                                     'investActivo': True,
                                     'irpfSelectorCuentaTarjeta': False,
                                     'kqofMaxConfigurableTimeout': 20000,
                                     'kqofReadTimeout': 10000,
                                     'libmcryptKey': 'D161B47194CCC0810B9CC0F59E122541738CB573AAA2D924A80A0FEAE711E25A06A13B5953CFBBC5C113FC3611947491DBF8DD3C95CB8582BD0A121761992A3CDF7B08C282F61A9C7A0DAAD7CC36C94F63B4B1EE313CD1970ED7649A3BDB878206A74CCA9F15A269DDF89E106A1F9140BF94B27F30710C5C9A7468AFBA22824BDF3E3053BB29952A9EFC59FCB6C2436AB97EF05BB320F28CF3EF50BC76CE2115D5EA9AA53174E089369EB74F7DFE0485F9CA68CA579C05B301063B29AF1EFE55A6F6229E5104593377A229A5978E306CAEA3DD011DBCD8F7F6784F9B05679D9477A5E80BE525A883B38C4614124A88EE13547014C7FB8C50CC5742ED3FE34A31',
                                     'loansPartialCancellationToggle': True,
                                     'loansToggle': True,
                                     'mailEnvioDocumentos': True,
                                     'manageMailEnax': True,
                                     'menurizacionArbol': True,
                                     'misRecibosClientFlow': False,
                                     'modalFondosYplanes': '960',
                                     'modoPlanContingencia': 'NORMAL',
                                     'mostrarBotonAdeudo': True,
                                     'mostrarHistoricoTransferencias': True,
                                     'mostrarTelefonos': True,
                                     'muestraGallegoYEuskera': False,
                                     'myRetirementUrl': 'https://www.jubilaciondefuturo.es',
                                     'navigateToTasksTimer': 2000,
                                     'newBannersHtml': True,
                                     'nivelSeguridadPanAnonimo': True,
                                     'novedadesFiscalesNew': True,
                                     'nuevaTrazabilidadMifidValores': True,
                                     'nuevoBotonIBAN': True,
                                     'numNotificacionesAMostrar': 2,
                                     'numOpAgilesAMostrar': 2,
                                     'ocFondosImagenCampana': 'https://www.bbva.es/estaticos/mult/Banner-Fondo-380x300.png',
                                     'openapiRestHost': 'https://openapi.bbva.com',
                                     'operationsAsoFichaActive': True,
                                     'operativaCitaPreviaSwitch': True,
                                     'operativaTurnoPrevioActivado': True,
                                     'operativasBloqueadas': ['mockcontratacion'],
                                     'pdfAmpliacionCapitales': True,
                                     'pdfMifidII': True,
                                     'planSimulationUrl': 'https://azure.afi.es/retirementsimulator/bbva/default.aspx',
                                     'planesMovimientosClientflow': True,
                                     'playSmartNotification1': True,
                                     'posicionAncla': 1000,
                                     'preloadHome': False,
                                     'procesosOclOneClick': True,
                                     'quitarBoton': True,
                                     'quitarConmutador': True,
                                     'rangoMaximoTransferencia': '999999.99',
                                     'reclamacionesEmailTelefono': 'true',
                                     'recuperarIbanContactosActivado': True,
                                     'returnBillToggle': True,
                                     'rutasBloqueadasRBA': ['tarjetas/financiacionrecibo',
                                                            'prestamoinmediato/coche',
                                                            'prestamoinmediato',
                                                            'traspaso/tarjetacuenta',
                                                            'valores/contenidos/fichavalor',
                                                            'financial-aggregator_enrollment'],
                                     'signatureIvrClientflowEnable': True,
                                     'signatureIvrEnable': True,
                                     'signatureIvrFunctionalities': 'cuentas/transferencias:cuentas/transferenciasnueva:cuentas/recargamovil:tarjetas/recargamovil:cuentas/efectivomovil:tarjetas/efectivomovil:areapersonal/contactos/anadir:tarjetas/recargas:tarjetas/descargartarjeta:cuentas/recargatarjeta:tarjetas/consultarcoverstarjeta:areapersonal/perfil/emails',
                                     'signatureIvrTimeout': '15000',
                                     'situationBalancesActive': True,
                                     'tabsEnabled': False,
                                     'tacticoCredito': True,
                                     'taggingAxesor': True,
                                     'tarjetasCambioDireccionEnBloqueo': True,
                                     'tarjetasCondiciones': True,
                                     'tealiumSwitchVersion': True,
                                     'timeKeepAliveSession': 240000,
                                     'timeSecureTimeoutSession': 10000,
                                     'timeTimeoutSession': 300000,
                                     'toggleAdjuntarAsociados': True,
                                     'toggleCambiarOficina': True,
                                     'toggleDatos': True,
                                     'toggleDatosEnax': True,
                                     'toggleInfoExtendBuscadorOficinas': True,
                                     'toggleListadoOficinas': True,
                                     'toggleListadoOficinasEnax': True,
                                     'toggleManageMailEnabled': True,
                                     'toggleOverdraftEnabled': True,
                                     'toggleOverdraftWarningMessageEnabled': True,
                                     'toggleTelefonos': True,
                                     'toggleTraspasoPlanes': True,
                                     'toggleWally': True,
                                     'toggleZeroAllowed': True,
                                     'topicThunderClientErrorsEnabled': True,
                                     'topicThunderEnabled': True,
                                     'traspasoPlanesOneClickToggle': True,
                                     'tridionEstaticosUrl': 'https://www.bbva.es',
                                     'twitterToggle': False,
                                     'typesIdSearchTask': 'A2E9A9B6-C939-1574-7CEE-86A69B7594DC|EE856451-14A6-BBAA-247B-2DDC98B2D54F|0BE81D89-3AE8-FE0C-9692-609013C9A126|E9A1DF55-6E47-AA21-8008-16DFAF4E73D8',
                                     'updateAccountTransactionsActive': True,
                                     'updateAccountTransactionsToggle': True,
                                     'urlImagenDeposito': 'https://www.bbva.es/estaticos/mult/landingDepositosVinculados.png',
                                     'urlMasInfoDescubierto': 'https://www.bbva.es/productos/ficha/servicio-descubierto-en-cuenta/t000000914&mb=si',
                                     'urlPrestamoCoche': 'https://www.bbva.es/particulares/hipotecas-prestamos/prestamos/simulador-prestamos/coche.jsp?mb=si',
                                     'urlPrestamoMultidestino': 'https://www.bbva.es/particulares/hipotecas-prestamos/prestamos/simulador-prestamos.jsp?mb=si',
                                     'urlTridionOCLBarra': 'https://www.bbva.es/sistema/crm/oclBarraYMasInformacion.jsp',
                                     'urlTridionOCLBocadillo': 'https://www.bbva.es/sistema/crm/oclBocadilloRollover.jsp',
                                     'urlTridionOCLModal': 'https://www.bbva.es/sistema/crm/encabezadoMasOfertas.jsp',
                                     'usabilidadTransferencias': True,
                                     'uxBrandPhase1': False,
                                     'uxBrandPhase1Employee': False,
                                     'valoresOPV': True,
                                     'virtualMailCxOn': True},
                       'root': {'JSONReportError': '',
                                'SESION_CADUCADA': False,
                                'agentLessParamName': 'kqof_agentless_params',
                                'alreadyLogged': False,
                                'dataLayerTime': 3000,
                                'endSessionWarningInterval': 230000,
                                'errorInInitialStaticLoad': False,
                                'extraDepsLoaded': False,
                                'flowExecutionKey': 'e1s1',
                                'initialLoading': True,
                                'initialStaticLoad': True,
                                'isLocalEnvironment': False,
                                'junction': '',
                                'langPath': '',
                                'lastUpdateTimeStamp': None,
                                'ltIE9': False,
                                'maxInactiveInterval': 290000,
                                'pdfStaticPath': '/estaticos/mult/',
                                'requestDomainAndProtocol': 'https://www.bbva.es',
                                'requestedUrl': False,
                                'spilangPath': '',
                                'startTime': '03/02/2019 02:51:28',
                                'title': 'BBVA',
                                'titleCloneId': '',
                                'tlgoBaseUrl': 'https://w3.grupobbva.com/TLGO/tlgo/oficinas',
                                'tlgoModalView': None,
                                'urlAnchor': None},
                       'userAppConfig': {'browserFamily': 'chrome',
                                         'browserMajorVersion': 25,
                                         'duplicatedUsersInSession': False,
                                         'os': 'WIN',
                                         'osName': 'Windows 7',
                                         'osVersion': '6.1',
                                         'scAuthStatus': True,
                                         'scAuthType': 'estandar',
                                         'scChannel': 'particulares',
                                         'scCodigoCliente': '003629321',
                                         'scUserId': '++Qaghmw6SVLHpJEd2ITmxJrzxOA1lE8',
                                         'sid': '70feb68f-875b-4e81-bbe1-3dd6343b4e35',
                                         'ttClientId': '++Qaghmw6SVLHpJEd2ITmxJrzxOA1lE8',
                                         'ttUserId': '',
                                         'ttVisitorId': ''}},
     'userInfo': {'birthDate': '1968-02-06T00:00:00.000+0100',
                  'branchId': '1150',
                  'caudalimetroCX': True,
                  'caudalimetroPilotoCX': True,
                  'cellPhoneChecked': True,
                  'cellPhoneNumber': '****0280',
                  'cellPhoneNumberToValidate': '',
                  'collectives': [{'codigoColectivo': None,
                                   'tipoPreferente': 'ATRIBUTOINDEFINIDO',
                                   'versionVigenteColectivo': None}],
                  'communicationLanguageIsoCode': 'ES',
                  'documentType': '1',
                  'emailAddress': '****lval@gmail.com',
                  'emailChecked': True,
                  'employeeCode': None,
                  'externalCustomerData': [{'aap': '00000074',
                                            'externalId': '02954689J77308422C2018243'},
                                           {'aap': '00000176',
                                            'externalId': '71336157I99181100C2018284'},
                                           {'aap': '00010000',
                                            'externalId': '02954689J24286963B2018243'},
                                           {'aap': '06190105',
                                            'externalId': '28746726F90648755A2014304'},
                                           {'aap': '06190105',
                                            'externalId': '28746726F90648755A2014349'},
                                           {'aap': '06190176',
                                            'externalId': '78709334E11425821D2018243'}],
                  'hasFinancedTransactions': False,
                  'hasPendingTasks': False,
                  'id': 'ES0182003629321C',
                  'idSegmento': '82',
                  'isEnrolled': False,
                  'managerId': '000451809',
                  'name': 'CATALINA',
                  'occupationTypeId': '1',
                  'pregrantedLoan': '1',
                  'segmentos': [{'codCriterioSegmento': 'GB', 'codSegmento': '82'}],
                  'surname1': 'GARCIA',
                  'surname2': 'MARTINEZ',
                  'userComingFromCx': True,
                  'userComingFromUnnim': False,
                  'userWithFileOperations': False,
                  'usuarioBloqueadoFactaCrs': False,
                  'usuarioBloqueadoRBA': False}}
